version: '3.7'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017

  application:
    image: tiktak
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      MONGODB_CONNECTION_STRING: mongodb://root:toor@mongo:27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMTP_SERVER: smtp://maildump:1025
      FROM_EMAIL: ''
    command: npm run start:dev

  maildump:
    image: ball6847/maildump
    restart: always
    ports:
      - 21025:1025

  redis:
    image: redis
    restart: always
    ports:
      - 26379:6379
